
$applyChangesToDefaultUser = 1                                    	# Applying this to default user will cause applying it to all new users created in the future

# ==========================================================================================================================================
# ==================================================== Remove apps installed by default ====================================================
# ==========================================================================================================================================

$removeApps = 1														# Set to 0 to not remove apps

$blockContentDelivery = 1											# Make sure random apps will not be automatically installed in the future
$removeAppsFromRegistry = 1											# Remove random apps registry keys

$appsToRemove = @(													# All uncommented apps will be removed

	# ====== Microsoft apps ======
    "Microsoft.549981C3F5F10" #Cortana
    "Microsoft.3DBuilder"
    "Microsoft.Appconnector"
    "Microsoft.BingFinance"
    "Microsoft.BingNews"
    "Microsoft.BingSports"
    "Microsoft.BingTranslator"
    "Microsoft.BingWeather"
	#"Microsoft.DesktopAppInstaller"
    "Microsoft.FreshPaint"
    "Microsoft.GamingServices"
	"Microsoft.GamingAp"
	"Microsoft.GetHelp"
	"Microsoft.Getstarted"
	"Microsoft.HEIFImageExtension"
	"Microsoft.Messaging"
    "Microsoft.Microsoft3DViewer"
	"Microsoft.MicrosoftEdge.Stable"
    "Microsoft.MicrosoftOfficeHub"
    "Microsoft.MicrosoftPowerBIForWindows"
    "Microsoft.MicrosoftSolitaireCollection"
    "Microsoft.MicrosoftStickyNotes"
    "Microsoft.MinecraftUWP"
	"Microsoft.MixedReality.Portal"
	#"Microsoft.MSPaint"
    "Microsoft.NetworkSpeedTest"
    "Microsoft.Office.OneNote"
	"Microsoft.OneConnect"
	"Microsoft.Pain"
    "Microsoft.People"
	"Microsoft.PowerAutomateDesktop"
    "Microsoft.Print3D"
	"Microsoft.ScreenSketch"
	"Microsoft.SecHealthUI"
    "Microsoft.SkypeApp"
	"Microsoft.StorePurchaseApp"
	"Microsoft.Todos"
	#"Microsoft.UI.Xaml.2.4"
	#"Microsoft.VCLibs.140.00"
	#"Microsoft.VP9VideoExtensions"
    "Microsoft.Wallet"
	"Microsoft.WebMediaExtensions"
	"Microsoft.WebpImageExtension"
    "Microsoft.Windows.Photos"
    "Microsoft.WindowsAlarms"
    #"Microsoft.WindowsCalculator"
    "Microsoft.WindowsCamera"
    "microsoft.windowscommunicationsapps"
	"Microsoft.WindowsFeedbackHub"
    "Microsoft.WindowsMaps"
	"Microsoft.WindowsNotepad"
    "Microsoft.WindowsPhone"
    "Microsoft.WindowsSoundRecorder"
    #"Microsoft.WindowsStore"
	#"Microsoft.WindowsTerminal"
    "Microsoft.Xbox.TCUI"
    "Microsoft.XboxApp"
    "Microsoft.XboxGameOverlay"
    "Microsoft.XboxGamingOverlay"
    "Microsoft.XboxSpeechToTextOverlay"
    "Microsoft.YourPhone"
    "Microsoft.ZuneMusic"
    "Microsoft.ZuneVideo"
    "Microsoft.CommsPhone"
    "Microsoft.ConnectivityStore"
    "Microsoft.GetHelp"
    "Microsoft.Getstarted"
    "Microsoft.Messaging"
    "Microsoft.Office.Sway"
    "Microsoft.OneConnect"
    "Microsoft.WindowsFeedbackHub"
    "Microsoft.Microsoft3DViewer"
    "Microsoft.MSPaint"
    "Microsoft.BingFoodAndDrink"
    "Microsoft.BingHealthAndFitness"
    "Microsoft.BingTravel"
    "Microsoft.WindowsReadingList"
    "Microsoft.MixedReality.Portal"
    "Microsoft.ScreenSketch"
    "Microsoft.XboxGamingOverlay"
	"Microsoft.XboxIdentityProvider"

	# ====== Sponsored apps ======
    "2FE3CB00.PicsArt-PhotoStudio"
    "46928bounde.EclipseManager"
    "4DF9E0F8.Netflix"
    "613EBCEA.PolarrPhotoEditorAcademicEdition"
    "6Wunderkinder.Wunderlist"
    "7EE7776C.LinkedInforWindows"
    "89006A2E.AutodeskSketchBook"
    "9E2F88E3.Twitter"
    "A278AB0D.DisneyMagicKingdoms"
    "A278AB0D.MarchofEmpires"
    "ActiproSOFTWARELLC.562882FEEB491"
    "CAF9E577.Plex"  
    "ClearChannelRadioDigital.iHeartRadio"
    "D52A8D61.FarmVille2CountryEscape"
    "D5EA27B7.Duolingo-LearnLanguagesforFree"
    "DB6EA5DB.CyberLinkMediaSuiteEssentials"
    "DolbyLaboratories.DolbyAccess"
    "DolbyLaboratories.DolbyAccess"
    "Drawboard.DrawboardPDF"
    "Facebook.Facebook"
    "Fitbit.FitbitCoach"
    "Flipboard.Flipboard"
    "GAMELOFTSA.Asphalt8Airborne"
    "KeeperSecurityInc.Keeper"
    "NORDCURRENT.COOKINGFEVER"
    "PandoraMediaInc.29680B314EFC2"
    "Playtika.CaesarsSlotsFreeCasino"
    "ShazamEntertainmentLtd.Shazam"
    "SlingTVLLC.SlingTV"
    "SpotifyAB.SpotifyMusic"
    "TheNewYorkTimes.NYTCrossword"
    "ThumbmunkeysLtd.PhototasticCollage"
    "TuneIn.TuneInRadio"
    "WinZipComputing.WinZipUniversal"
    "XINGAG.XING"
    "flaregamesGmbH.RoyalRevolt2"
    "king.com.*"
    "king.com.BubbleWitch3Saga"
    "king.com.CandyCrushSaga"
    "king.com.CandyCrushSodaSaga"
    "Microsoft.Advertising.Xaml"
)

$appKeysToRemove = @(												# All uncommented registry keys will be removed

	"HKCR:\Extensions\ContractId\Windows.BackgroundTasks\PackageId\46928bounde.EclipseManager_2.2.4.51_neutral__a5h4egax66k6y"
	"HKCR:\Extensions\ContractId\Windows.BackgroundTasks\PackageId\ActiproSOFTWARELLC.562882FEEB491_2.6.18.18_neutral__24pqs290vpjk0"
	"HKCR:\Extensions\ContractId\Windows.BackgroundTasks\PackageId\Microsoft.MicrosoftOfficeHub_17.7909.7600.0_x64__8wekyb3d8bbwe"
	"HKCR:\Extensions\ContractId\Windows.BackgroundTasks\PackageId\Microsoft.PPIProjection_10.0.15063.0_neutral_neutral_cw5n1h2txyewy"
	"HKCR:\Extensions\ContractId\Windows.BackgroundTasks\PackageId\Microsoft.XboxGameCallableUI_1000.15063.0.0_neutral_neutral_cw5n1h2txyewy"
	"HKCR:\Extensions\ContractId\Windows.BackgroundTasks\PackageId\Microsoft.XboxGameCallableUI_1000.16299.15.0_neutral_neutral_cw5n1h2txyewy"
	
	"HKCR:\Extensions\ContractId\Windows.File\PackageId\ActiproSOFTWARELLC.562882FEEB491_2.6.18.18_neutral__24pqs290vpjk0"
	
	"HKCR:\Extensions\ContractId\Windows.Launch\PackageId\46928bounde.EclipseManager_2.2.4.51_neutral__a5h4egax66k6y"
	"HKCR:\Extensions\ContractId\Windows.Launch\PackageId\ActiproSOFTWARELLC.562882FEEB491_2.6.18.18_neutral__24pqs290vpjk0"
	"HKCR:\Extensions\ContractId\Windows.Launch\PackageId\Microsoft.PPIProjection_10.0.15063.0_neutral_neutral_cw5n1h2txyewy"
	"HKCR:\Extensions\ContractId\Windows.Launch\PackageId\Microsoft.XboxGameCallableUI_1000.15063.0.0_neutral_neutral_cw5n1h2txyewy"
	"HKCR:\Extensions\ContractId\Windows.Launch\PackageId\Microsoft.XboxGameCallableUI_1000.16299.15.0_neutral_neutral_cw5n1h2txyewy"
	
	"HKCR:\Extensions\ContractId\Windows.PreInstalledConfigTask\PackageId\Microsoft.MicrosoftOfficeHub_17.7909.7600.0_x64__8wekyb3d8bbwe"
	   
	"HKCR:\Extensions\ContractId\Windows.Protocol\PackageId\ActiproSOFTWARELLC.562882FEEB491_2.6.18.18_neutral__24pqs290vpjk0"
	"HKCR:\Extensions\ContractId\Windows.Protocol\PackageId\Microsoft.PPIProjection_10.0.15063.0_neutral_neutral_cw5n1h2txyewy"
	"HKCR:\Extensions\ContractId\Windows.Protocol\PackageId\Microsoft.XboxGameCallableUI_1000.15063.0.0_neutral_neutral_cw5n1h2txyewy"
	"HKCR:\Extensions\ContractId\Windows.Protocol\PackageId\Microsoft.XboxGameCallableUI_1000.16299.15.0_neutral_neutral_cw5n1h2txyewy"
		   
	"HKCR:\Extensions\ContractId\Windows.ShareTarget\PackageId\ActiproSOFTWARELLC.562882FEEB491_2.6.18.18_neutral__24pqs290vpjk0"
)

# ==========================================================================================================================================
# ====================================================== Disable unnecessary features ======================================================
# ==========================================================================================================================================

$disableFeatures = 1												# Set to 0 to not disable the features

$featuresToDisable=@(												# All uncommented features will be disabled
	#"Printing-PrintToPDFServices-Features"
	"Printing-XPSServices-Features"
	"TelnetClient"
	"TFTP"
	#"LegacyComponents" #Paint, IE11, etc.
	"DirectPlay"
	"SimpleTCP"
	"Windows-Identity-Foundation"
	#"NetFx3"
	"WCF-HTTP-Activation"
	"WCF-NonHTTP-Activation"
	"IIS-WebServerRole"
	"IIS-WebServer"
	"IIS-CommonHttpFeatures"
	"IIS-HttpErrors"
	"IIS-HttpRedirect"
	"IIS-ApplicationDevelopment"
	"IIS-Security"
	"IIS-RequestFiltering"
	"IIS-NetFxExtensibility"
	"IIS-NetFxExtensibility45"
	"IIS-HealthAndDiagnostics"
	"IIS-HttpLogging"
	"IIS-LoggingLibraries"
	"IIS-RequestMonitor"
	"IIS-HttpTracing"
	"IIS-URLAuthorization"
	"IIS-IPSecurity"
	"IIS-Performance"
	"IIS-HttpCompressionDynamic"
	"IIS-WebServerManagementTools"
	"IIS-ManagementScriptingTools"
	"IIS-IIS6ManagementCompatibility"
	"IIS-Metabase"
	"WAS-WindowsActivationService"
	"WAS-ProcessModel"
	"WAS-NetFxEnvironment"
	"WAS-ConfigurationAPI"
	"IIS-HostableWebCore"
	#"WCF-Services45"
	"WCF-HTTP-Activation45"
	"WCF-TCP-Activation45"
	"WCF-Pipe-Activation45"
	"WCF-MSMQ-Activation45"
	#"WCF-TCP-PortSharing45"
	"IIS-StaticContent"
	"IIS-DefaultDocument"
	"IIS-DirectoryBrowsing"
	"IIS-WebDAV"
	"IIS-WebSockets"
	"IIS-ApplicationInit"
	"IIS-ASPNET"
	"IIS-ASPNET45"
	"IIS-ASP"
	"IIS-CGI"
	"IIS-ISAPIExtensions"
	"IIS-ISAPIFilter"
	"IIS-ServerSideIncludes"
	"IIS-CustomLogging"
	"IIS-BasicAuthentication"
	"IIS-HttpCompressionStatic"
	"IIS-ManagementConsole"
	"IIS-ManagementService"
	"IIS-WMICompatibility"
	"IIS-LegacyScripts"
	"IIS-LegacySnapIn"
	"IIS-FTPServer"
	"IIS-FTPSvc"
	"IIS-FTPExtensibility"
	"MSMQ-Container"
	"MSMQ-DCOMProxy"
	"MSMQ-Server"
	"MSMQ-HTTP"
	"MSMQ-Multicast"
	"MSMQ-Triggers"
	#"MediaPlayback"
	#"WindowsMediaPlayer"
	"MSRDC-Infrastructure"
	"TIFFIFilter"
	#"NetFx4-AdvSrvs"
	"NetFx4Extended-ASPNET45"
	"SMB1Protocol-Deprecation"
	"SearchEngine-Client-Package"
	#"MicrosoftWindowsPowerShellV2Root"
	#"MicrosoftWindowsPowerShellV2"
	"Client-ProjFS"
	"Windows-Defender-Default-Definitions"
	"WorkFolders-Client"
	"SMB1Protocol"
	"SMB1Protocol-Client"
	"SMB1Protocol-Server"
	"Internet-Explorer-Optional-amd64"
	#"Printing-Foundation-Features"
	#"Printing-Foundation-InternetPrinting-Client"
	"Printing-Foundation-LPDPrintService"
	"Printing-Foundation-LPRPortMonitor"
	"Microsoft-Windows-Subsystem-Linux"
	"HypervisorPlatform"
	"VirtualMachinePlatform"
)

# ==========================================================================================================================================
# ================================================================ Protect privacy =========================================================
# ==========================================================================================================================================

$protectPrivacy = 1													# Set to 0 to not protect privacy

$disalbeTelemetry = 1
$disableWindowsFeedback = 1
$disableCortana = 1
$disableInkingAndTypingPersonalization = 1
$disableBackgroundApps = 1
$disableAdID = 1
$disableSmartScreenFilter = 1
$disableP2PdeliveryOptimizationOutsideLAN = 1
$disableWifiSense = 1
$disableCollectingActivity = 1
$disableLocationTelemetry = 1
$blockPersonalizedContent = 1
$blockErrorReporting = 1
$blockDiagnosticTracker = 1
$blockRemoteAssistance = 1
$blockStorageSense = 1
$blockAutomaticMapsUpdate = 1
$disableOneDriveSync = 1

# ==========================================================================================================================================
# ==================================================================== Ban hosts ===========================================================
# ==========================================================================================================================================

$banHosts = 1														# Set to 0 to not protect privacy

$hostsToBan = @(													# All uncommented hosts will be banned
	"a-0001.a-msedge.net"
	"a-0002.a-msedge.net"
	"a-0003.a-msedge.net"
	"a-0004.a-msedge.net"
	"a-0005.a-msedge.net"
	"a-0006.a-msedge.net"
	"a-0007.a-msedge.net"
	"a-0008.a-msedge.net"
	"a-0009.a-msedge.net"
	"a-msedge.net"
	"a.ads1.msn.com"
	"a.ads2.msads.net"
	"a.ads2.msn.com"
	"a.rad.msn.com"
	"ac3.msn.com"
	"ad.doubleclick.net"
	"adnexus.net"
	"adnxs.com"
	"ads.msn.com"
	"ads1.msads.net"
	"ads1.msn.com"
	"aidps.atdmt.com"
	"aka-cdn-ns.adtech.de"
	"az361816.vo.msecnd.net"
	"az512334.vo.msecnd.net"
	"b.ads1.msn.com"
	"b.ads2.msads.net"
	"b.rad.msn.com"
	"bs.serving-sys.com"
	"c.atdmt.com"
	"c.msn.com"
	"ca.telemetry.microsoft.com"
	"cache.datamart.windows.com"
	"cdn.atdmt.com"
	"cds26.ams9.msecn.net"
	"choice.microsoft.com"
	"choice.microsoft.com.nsatc.net"
	"compatexchange.cloudapp.net"
	"corp.sts.microsoft.com"
	"corpext.msitadfs.glbdns2.microsoft.com"
	"cs1.wpc.v0cdn.net"
	"db3aqu.atdmt.com"
	"df.telemetry.microsoft.com"
	"diagnostics.support.microsoft.com"
	"ec.atdmt.com"
	"fe2.update.microsoft.com.akadns.net"
	"fe3.delivery.dsp.mp.microsoft.com.nsatc.net"
	"feedback.microsoft-hohm.com"
	"feedback.search.microsoft.com"
	"feedback.windows.com"
	"flex.msn.com"
	"g.msn.com"
	"h1.msn.com"
	"i1.services.social.microsoft.com"
	"i1.services.social.microsoft.com.nsatc.net"
	"lb1.www.ms.akadns.net"
	"live.rads.msn.com"
	"m.adnxs.com"
	"msedge.net"
	"msftncsi.com"
	"msnbot-65-55-108-23.search.msn.com"
	"msntest.serving-sys.com"
	"oca.telemetry.microsoft.com"
	"oca.telemetry.microsoft.com.nsatc.net"
	"pre.footprintpredict.com"
	"preview.msn.com"
	"rad.live.com"
	"rad.msn.com"
	"redir.metaservices.microsoft.com"
	"reports.wes.df.telemetry.microsoft.com"
	"schemas.microsoft.akadns.net"
	"secure.adnxs.com"
	"secure.flashtalking.com"
	"services.wes.df.telemetry.microsoft.com"
	"settings-sandbox.data.microsoft.com"
	"settings-win.data.microsoft.com"
	"sls.update.microsoft.com.akadns.net"
	"spynet2.microsoft.com"
	"spynetalt.microsoft.com"
	"sqm.df.telemetry.microsoft.com"
	"sqm.telemetry.microsoft.com"
	"sqm.telemetry.microsoft.com.nsatc.net"
	"ssw.live.com"
	"static.2mdn.net"
	"statsfe1.ws.microsoft.com"
	"statsfe2.update.microsoft.com.akadns.net"
	"statsfe2.ws.microsoft.com"
	"survey.watson.microsoft.com"
	"telecommand.telemetry.microsoft.com"
	"telecommand.telemetry.microsoft.com.nsatc.net"
	"telemetry.appex.bing.net"
	"telemetry.microsoft.com"
	"telemetry.urs.microsoft.com"
	"vortex-bn2.metron.live.com.nsatc.net"
	"vortex-cy2.metron.live.com.nsatc.net"
	"vortex-sandbox.data.microsoft.com"
	"vortex-win.data.microsoft.com"
	"vortex.data.microsoft.com"
	"watson.live.com"
	"watson.microsoft.com"
	"watson.ppe.telemetry.microsoft.com"
	"watson.telemetry.microsoft.com"
	"watson.telemetry.microsoft.com.nsatc.net"
	"wes.df.telemetry.microsoft.com"
	"www.msftncsi.com"
)


# ==========================================================================================================================================
# ============================================================= Disable services ===========================================================
# ==========================================================================================================================================

$disableServices = 1												# Set to 0 to not disable services

$servicesToDiable = @(												# All uncommented services will be disabled
	"BcastDVRUserService_48486de"
	"Browser"
	"diagtrack"
	"dmwappushservice"
	"edgeupdate"
	"edgeupdatem"
	"Fax"   
	"fhsvc"   
	"gupdate" 
	"gupdatem" 
	"lfsvc"
	"ClickToRunSvc"
	"MapsBroker"
	"MicrosoftEdgeElevationService"
	"MSDTC"
	"PeerDistSvc"
	"PhoneSvc"
	"RemoteAccess"
	"RemoteRegistry"
	"RetailDemo"
	"SCardSvr"
	"SEMgrSvc"
	"SysMain"
	"TapiSrv"
	"WbioSrv"
	"wcncsvc"
	"wercplsupport"
	"WerSvc"
	"winrm"
	"wisvc"
	"WMPNetworkSvc"
	"WpcMonSvc"
	"WpnService"
	"WSearch"
	"XblAuthManager"
	"XblGameSave"
	"XboxNetApiSvc"
    "XboxGipSvc"  
	"diagnosticshub.standardcollector.service"
)
